
import React from 'react';
import { Brain, Activity, Heart, AlertTriangle, Sparkles, TrendingUp, Info } from 'lucide-react';

export const PatientAIInsights: React.FC = () => {
  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Hero Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-tech-900 to-ai-800 text-white shadow-xl">
         <div className="absolute top-0 right-0 w-96 h-96 bg-white/5 rounded-full -mr-20 -mt-20 blur-3xl"></div>
         <div className="absolute bottom-0 left-0 w-64 h-64 bg-primary-500/20 rounded-full -ml-10 -mb-10 blur-3xl"></div>
         
         <div className="relative p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="max-w-lg">
               <div className="flex items-center space-x-2 mb-4 text-ai-300 font-bold uppercase tracking-widest text-xs">
                  <Sparkles size={14} /> <span>Gemini Powered Analysis</span>
               </div>
               <h1 className="text-3xl md:text-4xl font-bold mb-4">Your Health Intelligence</h1>
               <p className="text-gray-300 leading-relaxed">
                  Our AI continuously scans your uploaded records to find patterns, suggest preventative care, and alert you to potential risks.
               </p>
            </div>
            <div className="flex-shrink-0 bg-white/10 p-6 rounded-2xl backdrop-blur-sm border border-white/10">
               <div className="flex items-center gap-3 mb-2">
                  <div className="w-3 h-3 bg-green-400 rounded-full animate-pulse"></div>
                  <span className="font-bold text-lg">System Active</span>
               </div>
               <div className="text-xs text-gray-400">Last scan: 2 hours ago</div>
            </div>
         </div>
      </div>

      {/* Disclaimer */}
      <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg flex items-start">
         <Info className="text-yellow-600 mt-0.5 mr-3 flex-shrink-0" size={20} />
         <div>
            <h4 className="font-bold text-yellow-800 text-sm">AI Suggestions Only</h4>
            <p className="text-yellow-700 text-xs mt-1">
               These insights are generated by artificial intelligence based on your records. They are not a medical diagnosis. Always consult your doctor.
            </p>
         </div>
      </div>

      {/* Insights Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
         
         {/* Card 1: Medicine Patterns */}
         <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow group">
            <div className="flex items-center gap-4 mb-6">
               <div className="w-12 h-12 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Activity size={24} />
               </div>
               <div>
                  <h3 className="font-bold text-gray-900 text-lg">Medicine Optimization</h3>
                  <p className="text-xs text-gray-500">Based on 4 prescriptions</p>
               </div>
            </div>
            <div className="space-y-4">
               <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                  <div className="flex items-start gap-3">
                     <Sparkles size={16} className="text-ai-500 mt-1 flex-shrink-0" />
                     <div>
                        <p className="text-sm text-gray-700 font-medium mb-1">Interaction Alert</p>
                        <p className="text-xs text-gray-500 leading-relaxed">
                           You are taking Vitamin D3 supplements. Ensure you take them with a meal for better absorption, as suggested in your latest general checkup.
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>

         {/* Card 2: Health Risks */}
         <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow group">
            <div className="flex items-center gap-4 mb-6">
               <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Heart size={24} />
               </div>
               <div>
                  <h3 className="font-bold text-gray-900 text-lg">Risk Assessment</h3>
                  <p className="text-xs text-gray-500">Preventative Care</p>
               </div>
            </div>
            <div className="space-y-4">
               <div className="bg-gray-50 p-3 rounded-lg border border-gray-100">
                   <div className="flex items-start gap-3">
                     <AlertTriangle size={16} className="text-yellow-500 mt-1 flex-shrink-0" />
                     <div>
                        <p className="text-sm text-gray-700 font-medium mb-1">Cholesterol Trend</p>
                        <p className="text-xs text-gray-500 leading-relaxed">
                           Your last 2 lab reports show a slight increase in LDL levels. AI suggests reviewing your diet plan with a nutritionist.
                        </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>

         {/* Card 3: Visit Analytics */}
         <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow group">
            <div className="flex items-center gap-4 mb-6">
               <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <TrendingUp size={24} />
               </div>
               <div>
                  <h3 className="font-bold text-gray-900 text-lg">Visit Pattern</h3>
                  <p className="text-xs text-gray-500">Frequency Analysis</p>
               </div>
            </div>
            <div className="space-y-4">
               <p className="text-sm text-gray-600">
                  You visit the <span className="font-bold">Cardiologist</span> approximately every <span className="font-bold">6 months</span>.
               </p>
               <div className="w-full bg-gray-100 rounded-full h-2">
                  <div className="bg-blue-500 h-2 rounded-full w-3/4"></div>
               </div>
               <p className="text-xs text-gray-400 text-right">Next predicted visit: June 2024</p>
            </div>
         </div>

         {/* Card 4: Smart Recommendations */}
         <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow group">
            <div className="flex items-center gap-4 mb-6">
               <div className="w-12 h-12 rounded-xl bg-green-50 text-green-600 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Brain size={24} />
               </div>
               <div>
                  <h3 className="font-bold text-gray-900 text-lg">Smart Recommendations</h3>
                  <p className="text-xs text-gray-500">Lifestyle & Habits</p>
               </div>
            </div>
            <ul className="space-y-3">
               <li className="flex items-start gap-2 text-sm text-gray-600">
                  <span className="w-1.5 h-1.5 bg-green-500 rounded-full mt-1.5 flex-shrink-0"></span>
                  Increase water intake (Kidney function marker stable but low hydration detected).
               </li>
               <li className="flex items-start gap-2 text-sm text-gray-600">
                  <span className="w-1.5 h-1.5 bg-green-500 rounded-full mt-1.5 flex-shrink-0"></span>
                  Consider light physiotherapy for lumbar region based on MRI history.
               </li>
            </ul>
         </div>

      </div>
    </div>
  );
};
